### ISSUE TITLE
Fix Stress building by refactoring git fetch out of fab_cassandra.bootstrap

### ISSUE THREAD

**Issue by EnigmaCurry** [datastax/cstar_perf#104]
We are now relying on the git repo in ~/fab/cassandra.git for both stress and cassandra, so we should factor it out to it's own method.

Right now, stress building (since #88) is broken, because it does not do a fetch before building, so any new branches/shas are not known, erroring out:

```
Traceback (most recent call last):
  File "/home/ryan/git/cstar_perf/env/bin/cstar_perf_stress", line 9, in <module>
    load_entry_point('cstar-perf.tool==1.0', 'console_scripts', 'cstar_perf_stress')()
  File "/home/ryan/git/cstar_perf/tool/cstar_perf/tool/stress_compare.py", line 258, in main
    stress_compare(**cfg)
  File "/home/ryan/git/cstar_perf/tool/cstar_perf/tool/stress_compare.py", line 111, in stress_compare
    stress_shas = setup_stress(stress_revisions)
  File "/home/ryan/git/cstar_perf/tool/cstar_perf/tool/benchmark.py", line 406, in setup_stress
    revisions.update(build_stress(stress_revision))
  File "/home/ryan/git/cstar_perf/tool/cstar_perf/tool/benchmark.py", line 382, in build_stress
    raise AssertionError('Invalid stress_revision: {}'.format(stress_revision))
AssertionError: Invalid stress_revision: enigmacurry/stress-report-interval
```

Doing a manual fetch on ~/fab/cassandra.git is a temporary fix, but this needs to be done each time you need to use a new branch/sha

Because DSE also relies on stress, we should refactor the fetch code out of fab_cassandra.bootstrap and put it in fab_common.update_cassandra_git. We'll need to find all the places we call bootstrap and call this new method there too.

**Comment by aboudreault** [comment]
fixed
