### ISSUE TITLE
Docker frontend container fails with ID mismatch

### ISSUE THREAD

**Issue by mshuler** [datastax/cstar_perf#209]
```
[172.17.0.59] out: Installing collected packages: cstar-perf.frontend
[172.17.0.59] out:   Running setup.py develop for cstar-perf.frontend
[172.17.0.59] out: Successfully installed cstar-perf.frontend-1.0
[172.17.0.59] out: You are using pip version 8.1.1, however version 8.1.2 is available.
[172.17.0.59] out: You should consider upgrading via the 'pip install --upgrade pip' command.
[172.17.0.59] out: 

[172.17.0.59] Executing task 'generate_frontend_credentials'
[172.17.0.59] run: cstar_perf_server --get-credentials > ~/credentials.txt
test-frontend-00
[172.17.0.60] Executing task 'create_default_frontend_users'
[172.17.0.60] run: rm -f ~/pyscript.py
[172.17.0.60] run: echo '
from cstar_perf.frontend.server.model import Model
db = Model()
admin = db.create_user('\\''admin@example.com'\\'', '\\''Admin Full Name'\\'', ['\\''user'\\'','\\''admin'\\''])
db.set_user_passphrase('\\''admin@example.com'\\'', '\\''admin'\\'')
user = db.create_user('\\''user@example.com'\\'', '\\''User Full Name'\\'', ['\\''user'\\''])
db.set_user_passphrase('\\''user@example.com'\\'', '\\''user'\\'')
' >> "$(echo pyscript.py)"
[172.17.0.60] run: python pyscript.py
[172.17.0.60] out: INFO:cstar_perf.model:Initializing Model...
[172.17.0.60] out: INFO:cstar_perf.model:Creating new schema in keyspace : cstar_perf
[172.17.0.60] out: Traceback (most recent call last):
[172.17.0.60] out:   File "pyscript.py", line 3, in <module>
[172.17.0.60] out:     db = Model()
[172.17.0.60] out:   File "/home/cstar/git/cstar_perf/frontend/cstar_perf/frontend/server/model.py", line 138, in __init__
[172.17.0.60] out:     self.__shared_session = self.get_session()
[172.17.0.60] out:   File "/home/cstar/git/cstar_perf/frontend/cstar_perf/frontend/server/model.py", line 165, in get_session
[172.17.0.60] out:     self.__create_schema()
[172.17.0.60] out:   File "/home/cstar/git/cstar_perf/frontend/cstar_perf/frontend/server/model.py", line 181, in __create_schema
[172.17.0.60] out:     session.execute("CREATE TABLE tests (test_id timeuuid PRIMARY KEY, user text, cluster text, status text, test_definition text, completed_date timeuuid, progress_msg text);")
[172.17.0.60] out:   File "cassandra/cluster.py", line 1581, in cassandra.cluster.Session.execute (cassandra/cluster.c:27046)
[172.17.0.60] out:   File "cassandra/cluster.py", line 3145, in cassandra.cluster.ResponseFuture.result (cassandra/cluster.c:59905)
[172.17.0.60] out: cassandra.protocol.ServerError: <ErrorMessage code=0000 [Server error] message="java.lang.RuntimeException: java.util.concurrent.ExecutionException: org.apache.cassandra.exceptions.ConfigurationException: Column family ID mismatch (found 2b51d330-184d-11e6-a8ce-57aaa960d87b; expected 2b27dd00-184d-11e6-a8ce-57aaa960d87b)">
[172.17.0.60] out: 


Fatal error: run() received nonzero return code 1 while executing!

Requested: python pyscript.py
Executed: /bin/bash -l -c "python pyscript.py"

Aborting.
INFO:cstar_docker:Destroying test-frontend containers...
```

**Comment by mshuler** [comment]
This is with Docker version 1.6.2, build 7c8fca2 - I'll check this with a suggested source build of docker.
