### ISSUE TITLE
SSHException('EOF during negotiation') while running cstar_perf_bootstrap

### ISSUE THREAD

**Issue by alecswan** [datastax/cstar_perf#42]
I've been trying to get "cstar_perf_bootstrap cassandra-2.0.10" command to work following [this tutorial](http://datastax.github.io/cstar_perf/setup_cstar_perf_tool.html). At first I was getting errors with the script not being able to check out from Git, so I ran "git config --global url."https://".insteadOf git://" on all Cassandra nodes and it got me past the problem.

This time I am getting a similar error while running "cstar_perf_bootstrap cassandra-2.0.10" but I am not sure how I can work-around it or fix it:
[cnode3] run: ln -s /usr/share/java/jna.jar ~/fab/cassandra/lib/jna.jar
!!! Parallel execution exception under host u'cnode3':
Process cnode3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python2.7/dist-packages/fabric/tasks.py", line 239, in inner
    submit(task.run(*args, **kwargs))
  File "/usr/local/lib/python2.7/dist-packages/fabric/tasks.py", line 174, in run
    return self.wrapped(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/fabric/decorators.py", line 181, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cstar_perf/tool/fab_cassandra.py", line 327, in bootstrap
    fab.get('~/fab/cassandra/conf/cassandra.yaml', conf_file)
  File "/usr/local/lib/python2.7/dist-packages/fabric/network.py", line 647, in host_prompting_wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/fabric/operations.py", line 535, in get
    ftp = SFTP(env.host_string)
  File "/usr/local/lib/python2.7/dist-packages/fabric/sftp.py", line 30, in __init__
    self.ftp = connections[host_string].open_sftp()
  File "/usr/local/lib/python2.7/dist-packages/paramiko/client.py", line 379, in open_sftp
    return self._transport.open_sftp_client()
  File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 811, in open_sftp_client
    return SFTPClient.from_transport(self)
  File "/usr/local/lib/python2.7/dist-packages/paramiko/sftp_client.py", line 132, in from_transport
    return cls(chan)
  File "/usr/local/lib/python2.7/dist-packages/paramiko/sftp_client.py", line 101, in __init__
    raise SSHException('EOF during negotiation')
SSHException: EOF during negotiation
[alebedev@m0053118] out: fatal: unable to connect to github.com:
[alebedev@m0053118] out: github.com[0: 192.30.252.128]: errno=Connection timed out
[alebedev@m0053118] out: 
[alebedev@m0053118] out:

**Comment by EnigmaCurry** [comment]
I wonder if the versions of any of the dependencies are out of date. I notice from the traceback you're using libraries found in your system path. I would try installing cstar_perf inside a virtualenv to see if that works out better. I suspect it may be the paramiko library being out of date.

**Comment by EnigmaCurry** [comment]
That said, it does look like there's two issues going on in this log:

 * It can't copy the cassandra.yaml to cnode3, (which is why I suspect paramiko)
 * The error saying it timed out connecting to github is seemingly unrelated. Is 'git fetch apache' working from the ~/fab/cassandra.git directory?

**Comment by alecswan** [comment]
I ran "git config --global url."https://".insteadOf git://" on the VM where I installed cstar and it fixed the git connection problem.

However, I am still getting SSHException('EOF during negotiation') from paramiko even after upgrading paramiko as follows:

```
sudo pip install --upgrade paramiko
Requirement already up-to-date: paramiko in /usr/local/lib/python2.7/dist-packages
Collecting ecdsa>=0.11 from https://pypi.python.org/packages/2.7/e/ecdsa/ecdsa-0.13-py2.py3-none-any.whl#md5=a325d50195d049599f9b578ec4417bc6 (from paramiko)
  Downloading ecdsa-0.13-py2.py3-none-any.whl (86kB)
    100% |################################| 90kB 1.8MB/s 
Requirement already up-to-date: pycrypto!=2.4,>=2.1 in /usr/local/lib/python2.7/dist-packages (from paramiko)
Installing collected packages: ecdsa
  Found existing installation: ecdsa 0.12
    Uninstalling ecdsa-0.12:
      Successfully uninstalled ecdsa-0.12

Successfully installed ecdsa-0.13
```

**Comment by alecswan** [comment]
Apparently there was a misconfiguration of sftp server on all my VMs. I followed these instructions to fix it http://www.unix.com/302565302-post12.html
